# Generated by Django 5.1.1 on 2024-12-09 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_stafflist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stafflist",
            old_name="position",
            new_name="designation",
        ),
        migrations.AddField(
            model_name="stafflist",
            name="address",
            field=models.TextField(default="Unknown Address"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stafflist",
            name="phone_number",
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
