# Generated by Django 5.1.1 on 2024-12-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_student_updated_at_alter_student_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="father_name",
            field=models.CharField(default="Something", max_length=100),
        ),
    ]
