# Generated by Django 5.1.1 on 2024-12-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_student_father_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="father_name",
            field=models.CharField(max_length=100),
        ),
    ]
