# Generated by Django 5.1.1 on 2024-12-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_student_father_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="price",
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(max_length=50),
        ),
    ]
